# Generated by Django 3.2.5 on 2021-07-30 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Status',
            field=models.CharField(choices=[('pending', 'pending'), ('out for delivery', 'out for delivery'), ('delieverd', 'delievered')], max_length=200, null=True),
        ),
    ]
