# Generated by Django 3.2.5 on 2021-07-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application1', '0002_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date_created',
        ),
    ]
